### ISSUE TITLE
Not compatible with react native 0.71.1 : android compilation error

### ISSUE THREAD

**Issue by agjini** [DataDog/dd-sdk-reactnative#383]
Create a new react native 0.71.1 with react native cli.

`npx react-native init test`

add datadog dependency

`npm install @datadog/mobile-react-native`

And run

`
npm run start
npm run android
`

**Describe what happened**
The android build process failed with the following errors :

`
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081
e: /home/agjini/workspace/perso/liane/liane/node_modules/@datadog/mobile-react-native/android/src/main/kotlin/com/datadog/reactnative/DdSdk.kt: (183, 9): No value passed for parameter 'sessionReplayEnabled'
`

`
e: /home/agjini/workspace/perso/liane/liane/node_modules/@datadog/mobile-react-native/android/src/main/kotlin/com/datadog/reactnative/DdSdk.kt: (233, 21): Val cannot be reassigned
`

`
e: /home/agjini/workspace/perso/liane/liane/node_modules/@datadog/mobile-react-native/android/src/main/kotlin/com/datadog/reactnative/DdSdk.kt: (238, 21): Val cannot be reassigned
`

`
e: /home/agjini/workspace/perso/liane/liane/node_modules/@datadog/mobile-react-native/android/src/main/kotlin/com/datadog/reactnative/DdSdk.kt: (244, 21): Val cannot be reassigned
`

**Steps to reproduce the issue:**

**Describe what you expected:**

The compilation errors to be fixed

**Additional context**

`
"@datadog/mobile-react-native": "^1.2.0"
`

**Comment by louiszawadzki** [comment]
Hi @agjini, thanks for reporting this!

It's indeed a problem we did not anticipate with RN 0.71, it added the sonatype snapshots repo in the list of gradle repositories, which pulls our own dev snapshot builds.
A PR has been opened here: https://github.com/DataDog/dd-sdk-reactnative/pull/382, it will be fixed early next week in the next release.

In the meantime, you can solve the issue by patching the library with the code from the PR and running `(cd android && ./gradlew clean)` before building again.

Thanks a lot for your patience, I will let you know when this is fixed!

**Comment by agjini** [comment]
Thanks for your reactivity,

I'll be patient.

**Comment by louiszawadzki** [comment]
Hi,

This issue should be fixed in the new `1.2.1` release.
I'm going to mark the issue as closed, please feel free to reopen the issue if you encounter any trouble fixing it :)

**Comment by sourabhdadapure** [comment]
still facing this issue on :

`react-native:0.71.2`
`@datadog/mobile-react-native: 1.3.1`

**Comment by louiszawadzki** [comment]
Hi @sourabhdadapure, thanks for reaching out!

Unfortunately we're not able to reproduce this on our end. Do you make sure to run `(cd android && ./gradlew clean)` before building? 
If the issue persists, could you share your `android/build.gradle` and `android/app/build.gradle` files as well as the stacktrace of the error you are seeing?

Thanks a lot!

**Comment by sourabhdadapure** [comment]
Hi @louiszawadzki, sorry for the late response. This was happening bc we  upgraded from 0.68 to 0.71 and I was able to fix this by adding this`implementation("com.facebook.react:react-android")` to my `build.gradle`
