### ISSUE TITLE
update to 2.4.1 and not seeing tap event anymore 

### ISSUE THREAD

**Issue by wcastand** [DataDog/dd-sdk-reactnative#705]
### Describe the bug

i update to 2.4.1 in my branch and can't see tap event anymore (neither on datadog website or in the DEBUG mode)

after trying and rebuilding my app, looks like i can't get the tap event on 2.4.0 either when i build my expo app in development (simulator on ios)
i'm not exactly sure what is happening (i have no other deps changes in package.json)
it's working on production build from our latest build (last week) as far as i know and see on datadog. so not sure what is happening

i get the native tap event (back button for example) but not the react components currently.

### Reproduction steps

update to 2.4.1 on expo 51

### SDK logs

 DEBUG  DATADOG: Starting RUM View “/home” #(app)/(protected)/(tabs)/home
 DEBUG  DATADOG: Starting RUM View “/transfer” #(app)/(protected)/transfer

should have a tap event between those

### Expected behavior

to log Tap event again

### Affected SDK versions

2.4.1

### Latest working SDK version

2.4.0

### Did you confirm if the latest SDK version fixes the bug?

Yes

### Integration Methods

NPM

### React Native Version

0.74.3

### Device Information

testing on ios, real device and simulator

### Other relevant information

also i use bun neither npm or yarn, you probably need to udpate your template to add pnpm, bun, etc or put a free text field

**Comment by marco-saia-datadog** [comment]
Hello @wcastand 👋 😃 Did you solve the issue? Could you elaborate on the solution for future reference?

**Comment by wcastand** [comment]
no i didn't so far but didn't try all possible solution or more like at the time i didn't downgrade to previous 2.4.0 to see if it still works or not.

so far i don't know if it's the version upgrade, an other deps that would break datadog tap event or something that i do in dev mode or development mode on expo app, i keep testing and will post more here but so far can't get tap event anymore :/

but wanted to try all the thing and have a better idea of what is the issue or at least try to downgrade before making the issue and since you can't delete i closed and will re-open if i can't figure it out and have a better idea of what is the issue :)


EDIT:

i tried downgrading and forcing 2.4.0 and rebuild with no other dependency changes and i can't get the tap event to log ( i get native tap like back button on ios) but not my own button. not sure if it's because i'm in dev / simu or something else :/


current config is 
```ts

export const config = new DatadogProviderConfiguration(
	Env.DATADOG_API_KEY,
	Env.DATADOG_ENV,
	Env.DATADOG_APP_ID,
	true, // trackInteractions
	!__DEV__, // trackResources
	!__DEV__, // trackErrors
	TrackingConsent.GRANTED,
)

config.site = "EU1"
config.nativeCrashReportEnabled = true
config.nativeViewTracking = false
config.nativeInteractionTracking = true
config.trackBackgroundEvents = false
if (__DEV__) {
	config.uploadFrequency = UploadFrequency.FREQUENT
	config.batchSize = BatchSize.SMALL
	config.verbosity = SdkVerbosity.DEBUG
}
config.firstPartyHosts = ["green-got.com"]
config.sessionSamplingRate = 100

export const onSDKInitialized = () => {
	console.log("Datadog SDK initialized")
	DdRum.getCurrentSessionId().then((sessionId) => {
		if (sessionId) Intercom.updateUser({ customAttributes: { sessionId } })
	})
	DdSdkReactNative.setAttributes({
		appVersion: Constants.expoConfig?.version ?? "unknown",
		updateId,
		runtimeVersion,
	})
}

```

EDIT: i tried to build with xcode for a real device, put everything at true in the config initial and not use __DEV__ but still not getting tap events.

**Comment by marco-saia-datadog** [comment]
@wcastand Thank you for providing further information.

Did you update any other dependencies by chance?

We have recently worked on a PR that addresses a problem with tap actions not being reported in debug mode: https://github.com/DataDog/dd-sdk-reactnative/pull/697.

Therefore, if you see the taps being reported in Release mode, but not in Debug mode, it might be the same issue that has been already addressed in that PR :)

On that regard, we are preparing the release and it will be available very soon!

**Comment by wcastand** [comment]
must be that then, at first i was updating multiple dependencies but i tried with just datadog dep updated and the issue is the same, must be related to the issue you linked since only the tap event seems to not be registered and it works in production. will wait for the update to see if it works then :)

**Comment by marco-saia-datadog** [comment]
Hello @wcastand 👋 

We have released [v2.4.2](https://github.com/DataDog/dd-sdk-reactnative/releases/tag/2.4.2)! Please let us know if it fixes your issue :)

**Comment by wcastand** [comment]
i update and rebuild my expo app but still no tap event 

i get native button like back button and view event but no tap event. 

![Screenshot 2024-07-23 at 15 45 26](https://github.com/user-attachments/assets/1d1e003e-d956-42e3-9150-17397258891e)

**Comment by wcastand** [comment]
i still don't get the tap even in development. seems to work fine on production env/setup tho
using latest version 2.4.3
